CREATE FUNCTION FUNCTION2 (@A INT, @B INT)
RETURNS VARCHAR (30)
AS
BEGIN
DECLARE @ANS VARCHAR(30)
IF @A>@B
SET @ANS='A IS GREATER'
ELSE
SET @ANS='B IS GREATER'
RETURN @ANS
END



DECLARE @C VARCHAR(30)
SET @C=DBO.FUNCTION2(6,3)
PRINT @C