CREATE TABLE EMP8(ID INT,FNAME VARCHAR(20),LNAME VARCHAR(20),DEPT VARCHAR(20))
DROP TABLE EMP8
SELECT * FROM EMP8
DROP PROC P30
CREATE PROCEDURE P30
@EMP8ID INT,
 @EMP8FNAME VARCHAR(20),
 @EMP8LNAME VARCHAR(20),
 @EMP8DEPT VARCHAR(20)
 AS
 BEGIN
 INSERT INTO EMP8
 VALUES(@EMP8ID,@EMP8FNAME,@EMP8LNAME,@EMP8DEPT)
 END
 EXEC P30 123,'SURESH','PAL','TRAINING'